CREATE SEQUENCE GRANT_ACCESS_SRL_SEQ;

CREATE TABLE GRANT_ACCESS
(
  GRANT_ACCESS_SRL    NUMBER NOT NULL,
	PATTERNS            VARCHAR2 NOT NULL ,
	METHODS             VARCHAR2(150) NOT NULL ,
	ROLE_NAMES          VARCHAR2(150) NOT NULL ,
	ALLOW               CHAR(1) NULL DEFAULT 'Y' ,
	SEQ                 NUMBER NULL
);

ALTER TABLE GRANT_ACCESS
	ADD CONSTRAINT  GRANT_ACCESS_PK PRIMARY KEY (GRANT_ACCESS_SRL);

COMMENT ON TABLE GRANT_ACCESS IS '접근 권한 역활';

COMMENT ON COLUMN GRANT_ACCESS.GRANT_ACCESS_SRL IS '접근 권한 SRL';
COMMENT ON COLUMN GRANT_ACCESS.PATTERNS IS '접근 경로';
COMMENT ON COLUMN GRANT_ACCESS.METHODS IS '접근 방식';
COMMENT ON COLUMN GRANT_ACCESS.ROLE_NAMES IS '역활 부여';
COMMENT ON COLUMN GRANT_ACCESS.ALLOW IS '허용여부';
COMMENT ON COLUMN GRANT_ACCESS.SEQ IS '순번';

CREATE TABLE GRANT_ACCESS_PERMISSION_ROLE
(
  ROLE_NAME           VARCHAR2(50) NOT NULL,
	PATTERNS            VARCHAR2 NOT NULL ,
	METHODS             VARCHAR2(150) NOT NULL
);

ALTER TABLE GRANT_ACCESS_PERMISSION_ROLE
	ADD CONSTRAINT  GRANT_ACCESS_PERMISSION_ROLE_PK PRIMARY KEY (ROLE_NAME);

COMMENT ON TABLE GRANT_ACCESS_PERMISSION_ROLE IS '접근 권한 퍼미션';

COMMENT ON COLUMN GRANT_ACCESS_PERMISSION_ROLE.ROLE_NAME IS '역활';
COMMENT ON COLUMN GRANT_ACCESS_PERMISSION_ROLE.PATTERNS IS '접근 경로';
COMMENT ON COLUMN GRANT_ACCESS_PERMISSION_ROLE.METHODS IS '접근 방식';

CREATE TABLE GRANT_ACCESS_PERMISSION
(
  ROLE_NAME           VARCHAR2(50) NOT NULL,
	PATTERNS            VARCHAR2 NOT NULL ,
	METHODS             VARCHAR2(150) NOT NULL,
	PERMISSION          VARCHAR2(50) NOT NULL
);

ALTER TABLE GRANT_ACCESS_PERMISSION
	ADD CONSTRAINT  GRANT_ACCESS_PERMISSION_PK PRIMARY KEY (ROLE_NAME. PATTERNS);

COMMENT ON TABLE GRANT_ACCESS_PERMISSION IS '접근 퍼미션';

COMMENT ON COLUMN GRANT_ACCESS_PERMISSION.ROLE_NAME IS '역활';
COMMENT ON COLUMN GRANT_ACCESS_PERMISSION.PATTERNS IS '접근 경로';
COMMENT ON COLUMN GRANT_ACCESS_PERMISSION.METHODS IS '접근 방식';
COMMENT ON COLUMN GRANT_ACCESS_PERMISSION.PERMISSION IS '퍼미션 부여';

CREATE TABLE GRANT_BASIC_PERMISSION
(
	ROLE_NAME           VARCHAR2(50) NOT NULL ,
	PERMISSIONS         VARCHAR2(150) NULL
);

ALTER TABLE GRANT_BASIC_PERMISSION
	ADD CONSTRAINT  GRANT_BASIC_PERMISSION_PK PRIMARY KEY (ROLE_NAME);

COMMENT ON TABLE GRANT_BASIC_PERMISSION IS '기본 권한';

COMMENT ON COLUMN GRANT_BASIC_PERMISSION.ROLE_NAME IS '권한 역활';
COMMENT ON COLUMN GRANT_BASIC_PERMISSION.PERMISSIONS IS '권한 부여';


CREATE TABLE GRANT_USER_PERMISSION
(
  USER_ID      VARCHAR2(100) NOT NULL,
	ROLE_NAME    VARCHAR2(50) NOT NULL ,
	PERMISSIONS   VARCHAR2(150) NULL
);

ALTER TABLE GRANT_USER_PERMISSION
	ADD CONSTRAINT  GRANT_USER_PERMISSION_PK PRIMARY KEY (USER_ID, ROLE_NAME);

COMMENT ON TABLE GRANT_USER_PERMISSION IS '사용자 권한 부여';

COMMENT ON COLUMN GRANT_USER_PERMISSION.USER_ID IS '사용자 아이디';
COMMENT ON COLUMN GRANT_USER_PERMISSION.ROLE_NAME IS '역활';
COMMENT ON COLUMN GRANT_USER_PERMISSION.PERMISSIONS IS '권한 부여';