CREATE SEQUENCE GRANT_ACCESS_RULE_SRL_SEQ;

CREATE TABLE GRANT_ACCESS_RULE
(
	ACCESS_RULE_SRL    NUMBER NOT NULL,
	PATTERNS            VARCHAR2 NOT NULL ,
	METHODS             VARCHAR2(150) NOT NULL ,
	ROLE_NAMES          VARCHAR2(150) NOT NULL ,
	ALLOW               CHAR(1) NULL DEFAULT 'Y' ,
	SEQ                 NUMBER NULL
);

ALTER TABLE GRANT_ACCESS_RULE
	ADD CONSTRAINT  GRANT_ACCESS_RULE_PK PRIMARY KEY (ACCESS_RULE_SRL);

COMMENT ON TABLE GRANT_ACCESS_RULE IS '접근 권한 역활';

COMMENT ON COLUMN GRANT_ACCESS_RULE.ACCESS_RULE_SRL IS '접근 권한 SRL';
COMMENT ON COLUMN GRANT_ACCESS_RULE.PATTERNS IS '접근 경로';
COMMENT ON COLUMN GRANT_ACCESS_RULE.METHODS IS '접근 방식';
COMMENT ON COLUMN GRANT_ACCESS_RULE.ROLE_NAMES IS '역활 부여';
COMMENT ON COLUMN GRANT_ACCESS_RULE.ALLOW IS '허용여부';
COMMENT ON COLUMN GRANT_ACCESS_RULE.SEQ IS '순번';

CREATE TABLE GRANT_ACCESS_PERMIT
(
  ROLE_NAME           VARCHAR2(50) NOT NULL,
	PATTERNS            VARCHAR2 NOT NULL ,
	METHODS             VARCHAR2(150) NOT NULL ,
	SEQ                 NUMBER NULL
);

ALTER TABLE GRANT_ACCESS_PERMIT
	ADD CONSTRAINT  GRANT_ACCESS_PERMIT_PK PRIMARY KEY (ROLE_NAME);

COMMENT ON TABLE GRANT_ACCESS_PERMIT IS '접근 권한 퍼미션';

COMMENT ON COLUMN GRANT_ACCESS_PERMIT.ROLE_NAME IS '역활';
COMMENT ON COLUMN GRANT_ACCESS_PERMIT.PATTERNS IS '접근 경로';
COMMENT ON COLUMN GRANT_ACCESS_PERMIT.METHODS IS '접근 방식';
COMMENT ON COLUMN GRANT_ACCESS_PERMIT.SEQ IS '순번';

CREATE SEQUENCE GRANT_PERMIT_SRL_SEQ;

CREATE TABLE GRANT_RULE_PERMIT
(
	RULE_PERMIT_SRL     NUMBER NOT NULL,
	ROLE_NAME           VARCHAR2(50) NOT NULL,
	PATTERNS            VARCHAR2 NOT NULL ,
	METHODS             VARCHAR2(150) NOT NULL,
	PERMISSION          VARCHAR2(50) NOT NULL,
	SEQ                 NUMBER NULL
);

ALTER TABLE GRANT_RULE_PERMIT
	ADD CONSTRAINT  GRANT_RULE_PERMIT_PK PRIMARY KEY (RULE_PERMIT_SRL);

COMMENT ON TABLE GRANT_RULE_PERMIT IS '접근 퍼미션';

COMMENT ON COLUMN GRANT_RULE_PERMIT.ROLE_NAME IS '역활';
COMMENT ON COLUMN GRANT_RULE_PERMIT.PATTERNS IS '접근 경로';
COMMENT ON COLUMN GRANT_RULE_PERMIT.METHODS IS '접근 방식';
COMMENT ON COLUMN GRANT_RULE_PERMIT.PERMISSION IS '퍼미션 부여';
COMMENT ON COLUMN GRANT_RULE_PERMIT.SEQ IS '순번';

CREATE TABLE GRANT_BASIC_PERMIT
(
	ROLE_NAME           VARCHAR2(50) NOT NULL ,
	PERMISSIONS         VARCHAR2(150) NULL
);

ALTER TABLE GRANT_BASIC_PERMIT
	ADD CONSTRAINT  GRANT_BASIC_PERMIT_PK PRIMARY KEY (ROLE_NAME);

COMMENT ON TABLE GRANT_BASIC_PERMIT IS '기본 권한';

COMMENT ON COLUMN GRANT_BASIC_PERMIT.ROLE_NAME IS '권한 역활';
COMMENT ON COLUMN GRANT_BASIC_PERMIT.PERMISSIONS IS '권한 부여';


CREATE TABLE GRANT_USER_PERMIT
(
  USER_ID      VARCHAR2(100) NOT NULL,
	ROLE_NAME    VARCHAR2(50) NOT NULL ,
	PERMISSIONS   VARCHAR2(150) NULL
);

ALTER TABLE GRANT_USER_PERMIT
	ADD CONSTRAINT  GRANT_USER_PERMIT_PK PRIMARY KEY (USER_ID, ROLE_NAME);

COMMENT ON TABLE GRANT_USER_PERMIT IS '사용자 권한 부여';

COMMENT ON COLUMN GRANT_USER_PERMIT.USER_ID IS '사용자 아이디';
COMMENT ON COLUMN GRANT_USER_PERMIT.ROLE_NAME IS '역활';
COMMENT ON COLUMN GRANT_USER_PERMIT.PERMISSIONS IS '권한 부여';